// Auto-generated by scripts/assets.js

export const assets = {
  'bootsplash/logo': require('@/assets/bootsplash/logo.png'),
  'bootsplash/logo@1,5x': require('@/assets/bootsplash/logo@1,5x.png'),
  'bootsplash/logo@2x': require('@/assets/bootsplash/logo@2x.png'),
  'bootsplash/logo@3x': require('@/assets/bootsplash/logo@3x.png'),
  'bootsplash/logo@4x': require('@/assets/bootsplash/logo@4x.png'),
  'bootsplash/manifest': require('@/assets/bootsplash/manifest.json'),
};
